### ISSUE TITLE
DaggerConsumerComponent and DaggerWorkerComponent implementations

### ISSUE THREAD

**Issue by fjavierm** [petergu/aws-sqs-lambda-java#2]
Where are the implementations of the classes `DaggerConsumerComponent` and `DaggerWorkerComponent`?

**Comment by petergu** [comment]
They are Dagger 2 generated codes. Please see 

- [How do I see generated code in my IDE?](https://google.github.io/dagger/faq.html#how-do-i-see-generated-code-in-my-ide)
- [Is there any way of making IntelliJ IDEA recognizing Dagger 2 generated classes in a Java project?](https://stackoverflow.com/questions/33444356/is-there-any-way-of-making-intellij-idea-recognizing-dagger-2-generated-classes)

**Comment by fjavierm** [comment]
Thanks. I will take a look. I didn't know they were auto-generated classes
